-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20


NDefines.NGame.DAYS_BEHIND_PAUSE = 40
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 25


NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = -5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 5
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 25.0
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.DIPLOMAT_SPEED = 50.0
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -200
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 25
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.01
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = -5
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 3


NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 25
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.007
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 1
NDefines.NCountry.IDEA_TO_TECH = -0.02
NDefines.NCountry.PS_BUY_IDEA = 300
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NCountry.PS_RAISE_WAR_TAXES = 1
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.25
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 6
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 60
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 7
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = -5


NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.08
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.04
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20
NDefines.NEconomy.CARAVAN_FACTOR = 50.0
NDefines.NEconomy.CARAVAN_POWER_MAX = 10
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 7300


NDefines.NMilitary.SLACKEN_AP_DROP = 0.1
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -0.25
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 30.0
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 40
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0
NDefines.NMilitary.SIEGE_DISEASE_IMPACT = 0.1
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 5
NDefines.NMilitary.ASSAULT_ATTACKER_LOSS = 2.00
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.25
NDefines.NMilitary.CAVALRY_COST = 30.0
NDefines.NMilitary.TRANSPORT_COST = 6
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.5
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.COMBAT_DICE_SIDE = 8
NDefines.NMilitary.LEADER_MIN_PIPS = 2
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40


NDefines.NAI.DESIRED_SURPLUS = 0.12
NDefines.NAI.DESIRED_DEFICIT = 0.12
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.5
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.25
NDefines.NAI.DEVELOPMENT_CAP_BASE = 20
NDefines.NAI.DEVELOPMENT_CAP_MULT = 2
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.6
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.3