-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20


NDefines.NGame.DAYS_BEHIND_PAUSE = 30
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 25


NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = -5
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 5
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.EMPEROR_REVOKE_AUTHORITY_COST = 25.0
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.DIPLOMAT_SPEED = 100.0
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -200
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 25
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 6
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.02
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = -5
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 3
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 10


NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 25
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -10
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.01
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 1
NDefines.NCountry.IDEA_TO_TECH = -0.02
NDefines.NCountry.PS_BUY_IDEA = 400
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 33
NDefines.NCountry.PS_RAISE_WAR_TAXES = 1
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.25
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 6
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 60
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 5
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = -5
NDefines.NCountry.SCRIPTED_ADVISOR_DISCOUNT = 0.67
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = 0
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.34
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 8
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 10


NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.04
NDefines.NEconomy.NAVAL_TECH_MAINTENANCE_IMPACT = 0.02
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.1
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20
NDefines.NEconomy.CARAVAN_FACTOR = 50.0
NDefines.NEconomy.CARAVAN_POWER_MAX = 10
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 7300


NDefines.NMilitary.SLACKEN_AP_DROP = 0.1
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -0.25
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 30.0
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 40
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = 0
NDefines.NMilitary.SIEGE_DISEASE_IMPACT = 0.1
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 5
NDefines.NMilitary.ASSAULT_ATTACKER_LOSS = 1.25
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2
NDefines.NMilitary.CAVALRY_COST = 30.0
NDefines.NMilitary.TRANSPORT_COST = 6
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.0
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.DEFAULT_WARGOAL_BATTLESCORE_BONUS = 5
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50
NDefines.NMilitary.COMBAT_DICE_SIDE = 8
NDefines.NMilitary.LEADER_MIN_PIPS = 1
NDefines.NMilitary.LEADER_MAX_PIPS = 7
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.GARRISON_SIZE = 3000
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER = 0.34
NDefines.NMilitary.FORTRESS_COST = 0.25
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 1.5
NDefines.NMilitary.LIGHT_SHIP_TIME = 120
NDefines.NMilitary.TRANSPORT_TIME = 30
NDefines.NMilitary.EXTRA_LAND_REINFORCE_COST = 1.75


NDefines.NAI.DESIRED_SURPLUS = 0.12
NDefines.NAI.DESIRED_DEFICIT = 0.12
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MAX = 0.66
NDefines.NAI.ADVISOR_BUDGET_FRACTION_MIN = 0.33
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 80.0
NDefines.NAI.DEVELOPMENT_CAP_BASE = 15
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.6
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.3
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50.0
NDefines.NAI.AGGRESSIVENESS = 600
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 300